shop-asp-mvc/Controllers/TimKiemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using shop_asp_mvc.Models;
using PagedList;

namespace shop_asp_mvc.Controllers
{
    public class TimKiemController : Controller
    {
        QLBanHangEntities db = new QLBanHangEntities();
        [HttpGet]
        public ActionResult KQTimKiem(string sTuKhoa, int? page)
        {
            if (Request.HttpMethod != "GET")
            {
                page = 1;
            }
            int pageSize = 6;
            int pageNumber = (page ?? 1);

            var lstSP = db.SanPhams.Where(n => n.TenSP.Contains(sTuKhoa));
            ViewBag.TuKhoa = sTuKhoa;
            return View(lstSP.OrderBy(n => n.TenSP).ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        public ActionResult LayTuKhoaTimKiem(string sTuKhoa)
        {
            
            return RedirectToAction("KQTimKiem",new { @sTuKhoa = sTuKhoa });
        }
        public ActionResult KQTimKiemPartial(string sTuKhoa)
        {
            var lstSP = db.SanPhams.Where(n => n.TenSP.Contains(sTuKhoa));
            ViewBag.TuKhoa = sTuKhoa;
            return PartialView(lstSP.OrderBy(n=>n.DonGia));
        }
    }
}

shop-asp-mvc/Views/TimKiem/KQTimKiem.cshtml
@using shop_asp_mvc.Models
@using PagedList.Mvc
@model PagedList.IPagedList<SanPham>
@{
    ViewBag.Title = "KQTimKiem";
    Layout = "~/Views/Layout/ProductLayout.cshtml";
}
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
@using (Ajax.BeginForm("KQTimKiemPartial", "TimKiem", new AjaxOptions { UpdateTargetId = "KQTimKiem", InsertionMode = InsertionMode.Replace }))
{
    <input type="text" class="txtTimKiem" name="sTuKhoa" value="" placeholder="Nhập vào tên sản phẩm cần tìm" />
    <input type="submit" id="btnTimKiem" value="Tìm kiếm" />
}
<div id="KQTimKiem">
    <h2>Danh sách sản phẩm</h2>
    </br>
    <div class="col-md-9 product1">
        <div class=" bottom-product">
            @foreach (var item in Model.OrderBy(n => n.DonGia))
            {
                <div class="col-md-4 bottom-cd simpleCart_shelfItem">
                    <div class="product-at ">
                        <a href="@Url.Action("ThemGioHang","GioHang",new {@MaSP = item.MaSP,@strURL = Request.Url.ToString() })">
                            <img class="img-responsive" src="@Url.Content("~/Content/HinhAnhSP/" + item.HinhAnh)" alt="" style="width = 150px;height=150px;">
                            <div class="pro-grid">
                                <span class="buy-in"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Đặt mua</font></font></span>
                            </div>
                        </a>
                    </div>
                    <p class="tun"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Một thực tế đã được thiết lập từ lâu rằng một người đọc</font></font></p>
                    <a href="@Url.Action("ThemGioHang","GioHang",new { @MaSP = item.MaSP, @strURL = Request.Url.ToString() })" class="item_add"><p class="number item_price"><i> </i><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">@item.DonGia.Value.ToString("#,##") VND</font></font></p></a>
                    @Ajax.ActionLink("Thêm giỏ hàng Ajax", "ThemGioHangAjax", "GioHang", new { @MaSP = item.MaSP, @strURL = Request.Url.ToString() }, new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "divGioHang", InsertionMode = InsertionMode.Replace }, null)
                </div>

            }
            <div class="clearfix"> </div>


        </div>

    </div>
    <div class="dlink">
        Trang @(Model.PageCount<Model.PageNumber?0:Model.PageNumber)/@Model.PageCount
        @Html.PagedListPager(Model, page => Url.Action("KQTimKiem", new { page = page, @sTuKhoa = ViewBag.TuKhoa }))
    </div>
</div>

shop-asp-mvc/Views/TimKiem/KQTimKiemPartial.cshtml
@using shop_asp_mvc.Models
@model IEnumerable<SanPham>

@{
    int iDem = 0;
    int iSLSanPhamTrenTrang = 6;
    int iTrang = 1;
}

<div class="col-md-9 product1">
    <div class=" bottom-product">
        @foreach (var item in Model.OrderBy(n => n.DonGia))
        {
            if (iDem % iSLSanPhamTrenTrang == 0 && iDem != 0)
            {
                iTrang++;
            }
            <div class="@Url.Content("col-md-4 bottom-cd simpleCart_shelfItem Trang"+iTrang.ToString())">
                <div class="product-at ">
                    <a href="@Url.Action("ThemGioHang","GioHang",new {@MaSP = item.MaSP,@strURL = Request.Url.ToString() })">
                        <img class="img-responsive" src="@Url.Content("~/Content/HinhAnhSP/" + item.HinhAnh)" alt="" style="width = 150px;height=150px;">
                        <div class="pro-grid">
                            <span class="buy-in"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Đặt mua</font></font></span>
                        </div>
                    </a>
                </div>
                <p class="tun"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Một thực tế đã được thiết lập từ lâu rằng một người đọc</font></font></p>
                <a href="@Url.Action("ThemGioHang","GioHang",new { @MaSP = item.MaSP, @strURL = Request.Url.ToString() })" class="item_add"><p class="number item_price"><i> </i><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">@item.DonGia.Value.ToString("#,##") VND</font></font></p></a>
                @Ajax.ActionLink("Thêm giỏ hàng Ajax", "ThemGioHangAjax", "GioHang", new { @MaSP = item.MaSP, @strURL = Request.Url.ToString() }, new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "divGioHang", InsertionMode = InsertionMode.Replace }, null)
            </div>
            iDem++;
        }
        <div class="clearfix"> </div>

        <div class="Trang">
            @for (int i = 1; i <= iTrang; i++)
            {
                <a class="linkTrang" data-sotrang="@Url.Content("Trang"+i) " href="#">
                    @i
                </a>
            }

        </div>
    </div>

</div>
<style>
    .simpleCart_shelfItem {
        display: none;
    }

    .Trang1 {
        display: block;
    }
</style>
<script>
    $('.linkTrang').click(function () {
        $(".simpleCart_shelfItem").hide();
        var soTrang = $(this).attr("data-sotrang");
        $("@Url.Content("." + soTrang)").show();
    });
</script>